stages:
  - generate
  - test
  - publish

.base:
  tags:
    - small
  image: $CI_REGISTRY/weclapp_ops/base_images/node:latest-lts-alpine

.npm:defaults:
  extends: .base
  cache:
    key: node_modules_cache
    policy: pull
    paths:
    - node_modules/
  before_script:
    - npm install --unsafe-perm --prefer-offline --no-audit
    - npm prune

generate:
  extends: .npm:defaults
  stage: generate
  artifacts:
    expire_in: 4 weeks
    paths:
      - sdk
  variables:
    SRC_OPENAPI: "./openapi.json"
    SDK_VERSION: "1.0.0"
    SDK_REPOSITORY: "./sdk"
  script: |
    npm run import:swagger
    npm run gen:start
    npm run sdk:build

test:
  extends: .npm:defaults
  stage: test
  dependencies: [ 'generate' ]
  script: npm run test

lint:
  extends: .npm:defaults
  stage: test
  dependencies: [ 'generate' ]
  script: npm run lint:ts

publish:repository:
  extends: .base
  stage: publish
  dependencies: [ 'generate' ]
  script: |
    git clone "https://$SDK_GIT_USER:$SDK_GIT_PASS@gitlab.internal.weclapp.com/weclapp/frontend/sdk.git" sdk-remote --depth 1
    cp -r sdk/* sdk-remote
    cd sdk-remote
    git config user.email "noreply@weclapp.com"
    git config user.name "$SDK_GIT_USER"
    git add .
    git commit -m "$CI_COMMIT_SHA"
    git push "https://$SDK_GIT_USER:$SDK_GIT_PASS@gitlab.internal.weclapp.com/weclapp/frontend/sdk.git" master
