stages:
  - generate
  - test
  - publish

.npm:defaults:
  tags: ['small']
  image: $CI_REGISTRY/weclapp_ops/base_images/node:latest-14-alpine-npm7
  cache:
    key: node_modules_cache
    policy: pull
    paths:
      - node_modules/
  before_script:
    - npm install --unsafe-perm --prefer-offline --no-audit
    - npm prune

.publish:defaults:
  tags: ['tiny']
  stage: publish
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never

generate:
  extends: .npm:defaults
  stage: generate
  cache:
    key: node_modules_cache
    policy: pull-push
    paths:
      - node_modules/
  artifacts:
    expire_in: 4 weeks
    paths:
      - sdk
  variables:
    NODE_ENV: development
  script: |
    npm run cli:build
    ./bin/cli.js "$TEST_DOMAIN" --key "$TEST_API_KEY" --include-hidden

test:
  extends: .npm:defaults
  stage: test
  dependencies: ['generate']
  script: npm test

lint:
  extends: .npm:defaults
  stage: test
  dependencies: ['generate']
  script: npm run lint
