stages:
  - build
  - test

.npm:defaults:
  tags:
    - small
  image: $CI_REGISTRY/weclapp_ops/base_images/node:latest-lts-alpine
  cache:
    key: node_modules_cache
    policy: pull
    paths:
    - node_modules/
  before_script:
    - npm install --unsafe-perm --prefer-offline --no-audit
    - npm prune

lint:
  extends: .npm:defaults
  stage: test
  needs: ["build"]
  script: npm run lint:ts

test:
  extends: .npm:defaults
  stage: test
  needs: ["build"]
  script: npm run test

build:
  extends: .npm:defaults
  stage: build
  artifacts:
    paths:
      - sdk
  variables:
    SRC_OPENAPI: "./openapi.json"
    SDK_VERSION: "1.0.0"
    SDK_REPOSITORY: "./sdk"
  script: |
    npm run import:swagger
    npm run gen:start
    npm run sdk:build
