stages:
  - build
  - generate
  - lint
  - publish

.npm:defaults:
  tags:
    - small
  image: $CI_REGISTRY/weclapp_ops/base_images/node:latest-14-alpine-npm7
  cache:
    key: node_modules_cache
    policy: pull
    paths:
      - node_modules/

build:
  extends: .npm:defaults
  stage: build
  artifacts:
    expire_in: 4 weeks
    paths:
      - lib
  script:
    - npm install --unsafe-perm --prefer-offline --no-audit
    - npm prune

generate:
  extends: .npm:defaults
  stage: generate
  dependencies:
    - build
  artifacts:
    expire_in: 4 weeks
    paths:
      - sdk
  variables:
    NODE_ENV: development
  script: ./bin/cli.js --from-env --include-hidden

lint:
  extends: .npm:defaults
  stage: lint
  dependencies:
    - generate
  script: npm run lint

publish:
  tags:
    - tiny
  stage: publish
  image: $CI_REGISTRY/weclapp_ops/base_images/node:latest-14-alpine-npm7
  rules:
    # Only allow publishing if tag matches semantic versioning (v1.0.0)
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+[.][0-9]+[.][0-9]+$/'
    - when: never
  dependencies:
    - build
  variables:
    GITLAB_AUTH_TOKEN: $CI_JOB_TOKEN
  script: npm publish